resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

resources:

- name: flight-school
  type: git
  source:
    uri: {{uri}}
    branch: master

- name: flight-school-pr
  type: pull-request
  source:
    uri: {{uri}}
    access_token: {{access_token}}
    repo: aguimaraes/flight-school
        
jobs:

- name: flight-school-master
  plan:
  - get: flight-school
    trigger: true
  - task: master tests
    file: flight-school/ci/tasks/test-master.yml

- name: pr
  plan:
  - get: flight-school-pr
    trigger: true
  - put: flight-school-pr
    params:
      path: flight-school-pr
      status: pending

  - task: tests
    file: flight-school-pr/ci/tasks/test-pr.yml
    on_success:
        put: flight-school-pr
        params:
          path: flight-school-pr
          status: success
    on_failure:
      put: flight-school-pr
      params:
        path: flight-school-pr
        status: failure