resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

resources:

- name: master-resource
  type: git
  source:
    uri: {{uri}}
    branch: master

- name: pr-resource
  type: pull-request
  source:
    uri: {{uri}}
    access_token: {{access_token}}
    repo: aguimaraes/flight-school
        
jobs:

- name: commit-to-master
  plan:
  - get: master-resource
    trigger: true
  - task: test
    file: master-resource/ci/tasks/test-master.yml

- name: pr-changed
  plan:
  - get: pr-resource
    trigger: true
  - put: pr-resource
    params:
      path: pr-resource
      status: pending

  - task: test
    file: pr-resource/ci/tasks/test-pr.yml
    on_success:
        put: pr-resource
        params:
          path: pr-resource
          status: success
    on_failure:
      put: pr-resource
      params:
        path: pr-resource
        status: failure